# Generated by Django 3.1.4 on 2020-12-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mtg_Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mtg_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('lang', models.CharField(blank=True, max_length=32)),
                ('type_line', models.CharField(blank=True, max_length=254)),
                ('oracle_text', models.CharField(blank=True, max_length=254)),
                ('power', models.CharField(blank=True, max_length=8)),
                ('toughness', models.CharField(blank=True, max_length=8)),
                ('colors', models.JSONField(default=list)),
                ('color_identity', models.JSONField(default=list)),
                ('rarity', models.CharField(blank=True, max_length=8)),
                ('collector_number', models.CharField(blank=True, max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('artist', models.CharField(blank=True, max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('mtg_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.mtg_sets')),
                ('sales_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sales_category')),
            ],
        ),
    ]
