# Generated by Django 3.1.4 on 2020-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201221_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg_cards',
            name='power',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mtg_cards',
            name='rarity',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mtg_cards',
            name='toughness',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
