# Generated by Django 3.1.4 on 2020-12-21 11:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201221_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg_cards',
            name='color_identity',
            field=models.JSONField(default=products.models.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='mtg_cards',
            name='colors',
            field=models.JSONField(default=products.models.jsonfield_default_value),
        ),
    ]
