# Generated by Django 3.1.4 on 2020-12-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201221_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtg_cards',
            options={'verbose_name_plural': 'Mtg_Cards'},
        ),
        migrations.AlterModelOptions(
            name='mtg_sets',
            options={'verbose_name_plural': 'Mtg_Sets'},
        ),
        migrations.AlterModelOptions(
            name='sales_category',
            options={'verbose_name_plural': 'Sales_Categories'},
        ),
        migrations.AddField(
            model_name='mtg_cards',
            name='card_condition',
            field=models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('light_played', 'Light Played'), ('played', 'Played'), ('poor', 'Poor')], default='mint', max_length=12),
        ),
    ]
