# Generated by Django 3.1.4 on 2020-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201224_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg_cards',
            name='card_collection_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('showcase', 'Showcase'), ('expedition', 'Expedition'), ('textless', 'Textless')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='mtg_cards',
            name='card_print',
            field=models.CharField(choices=[('non_foil', 'Non-Foil'), ('foil', 'Foil')], default='non_foil', max_length=12),
        ),
    ]
